# Copyright (c) 2025 Erick Bourgeois, firestoned
# SPDX-License-Identifier: MIT

name: 'Security Vulnerability Scan'
description: 'Scans Rust dependencies with cargo-audit and fails on any vulnerabilities'
author: 'Erick Bourgeois <erick@firestoned.io>'

branding:
  icon: 'shield'
  color: 'red'

inputs:
  cargo-audit-version:
    description: 'Version of cargo-audit to install'
    required: false
    default: '0.22.0'
  upload-artifact-name:
    description: 'Name for the audit report artifact'
    required: false
    default: 'cargo-audit-report'

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Cache cargo-audit binary
      uses: actions/cache@v4
      id: cache-cargo-audit
      with:
        path: ~/.cargo/bin/cargo-audit
        key: ${{ runner.os }}-cargo-audit-${{ inputs.cargo-audit-version }}
        restore-keys: |
          ${{ runner.os }}-cargo-audit-

    - name: Install cargo-audit
      if: steps.cache-cargo-audit.outputs.cache-hit != 'true'
      shell: bash
      run: cargo install cargo-audit --version ${{ inputs.cargo-audit-version }} --locked --force

    - name: Run cargo audit (JSON output for reporting)
      id: audit_json
      shell: bash
      run: |
        cargo audit --json > audit-report.json
        cat audit-report.json

    - name: Run cargo audit (fail on vulnerabilities)
      shell: bash
      run: |
        echo "Checking for CRITICAL and HIGH vulnerabilities..."
        cargo audit --deny warnings

    - name: Upload audit report as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.upload-artifact-name }}
        path: audit-report.json
