# Copyright (c) 2025 Erick Bourgeois, firestoned
# SPDX-License-Identifier: MIT

name: 'Extract Version Information'
description: 'Extracts version, tag name, and image tags for consistent use across workflows'
author: 'Erick Bourgeois'

branding:
  icon: 'tag'
  color: 'blue'

inputs:
  repository:
    description: 'Repository name (e.g., firestoned/myapp) - used for image repository naming'
    required: true
  workflow-type:
    description: 'Workflow type: main, pr, or release'
    required: true
  pr-number:
    description: 'PR number (only for pr workflow)'
    required: false
  release-tag:
    description: 'Release tag name (only for release workflow)'
    required: false
  image-suffix:
    description: 'Image suffix for variant (e.g., "" or "-distroless")'
    required: false
    default: ''

outputs:
  version:
    description: 'Semantic version (e.g., 1.2.3)'
    value: ${{ steps.extract.outputs.version }}
  tag-name:
    description: 'Git tag name (e.g., v1.2.3)'
    value: ${{ steps.extract.outputs.tag-name }}
  image-tag:
    description: 'Docker image tag (e.g., main-2025.12.17, pr-42, v0.2.0)'
    value: ${{ steps.extract.outputs.image-tag }}
  image-repository:
    description: 'Docker repository name (e.g., firestoned/myapp or firestoned/myapp-distroless)'
    value: ${{ steps.extract.outputs.image-repository }}
  short-sha:
    description: 'Short 7-character SHA'
    value: ${{ steps.extract.outputs.short-sha }}

runs:
  using: 'composite'
  steps:
    - name: Extract version information
      id: extract
      shell: bash
      run: |
        # Extract short SHA (first 7 characters)
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        echo "short-sha=${SHORT_SHA}" >> $GITHUB_OUTPUT

        # Determine repository name based on image suffix
        BASE_REPO="${{ inputs.repository }}"
        if [ "${{ inputs.image-suffix }}" = "-distroless" ]; then
          IMAGE_REPOSITORY="${BASE_REPO}-distroless"
        else
          IMAGE_REPOSITORY="${BASE_REPO}"
        fi
        echo "image-repository=${IMAGE_REPOSITORY}" >> $GITHUB_OUTPUT

        case "${{ inputs.workflow-type }}" in
          release)
            # Release workflow: extract from release tag
            # Tag format: v0.2.0 (no date)
            TAG_NAME="${{ inputs.release-tag }}"
            VERSION="${TAG_NAME#v}"
            IMAGE_TAG="${TAG_NAME}"
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "tag-name=${TAG_NAME}" >> $GITHUB_OUTPUT
            echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
            echo "Release: version=${VERSION}, tag=${TAG_NAME}, image=${IMAGE_REPOSITORY}:${IMAGE_TAG}"
            ;;

          pr)
            # PR workflow: use pr-NUMBER format
            # Tag format: pr-42
            VERSION="pr-${{ inputs.pr-number }}"
            TAG_NAME="pr-${{ inputs.pr-number }}"
            IMAGE_TAG="pr-${{ inputs.pr-number }}"
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "tag-name=${TAG_NAME}" >> $GITHUB_OUTPUT
            echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
            echo "PR: version=${VERSION}, tag=${TAG_NAME}, image=${IMAGE_REPOSITORY}:${IMAGE_TAG}"
            ;;

          main)
            # Main branch: use main-YYYY.MM.DD format
            # Tag format: main-2025.12.17
            DATE=$(date +%Y.%m.%d)
            VERSION="0.0.0-main.${DATE}.${{ github.run_number }}"
            TAG_NAME="main-${DATE}"
            IMAGE_TAG="main-${DATE}"
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "tag-name=${TAG_NAME}" >> $GITHUB_OUTPUT
            echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
            echo "Main: version=${VERSION}, tag=${TAG_NAME}, image=${IMAGE_REPOSITORY}:${IMAGE_TAG}"
            ;;

          *)
            echo "Error: Invalid workflow-type '${{ inputs.workflow-type }}'. Must be: main, pr, or release"
            exit 1
            ;;
        esac
