# Copyright (c) 2025 Erick Bourgeois, firestoned
# SPDX-License-Identifier: MIT

name: 'Setup Rust Build Environment'
description: 'Sets up Rust toolchain with caching for multi-architecture builds'
author: 'Erick Bourgeois <erick@firestoned.io>'

branding:
  icon: 'package'
  color: 'orange'

inputs:
  target:
    description: 'Rust target triple (e.g., x86_64-unknown-linux-gnu)'
    required: true
  cache-key:
    description: 'Additional cache key component'
    required: false
    default: ''
  cross-version:
    description: 'Version of cross to install for ARM64 builds'
    required: false
    default: 'v0.2.5'
  components:
    description: 'Comma-separated list of components to install (e.g., rustfmt, clippy)'
    required: false
    default: 'rustfmt, clippy'

runs:
  using: composite
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.target }}
        components: ${{ inputs.components }}

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ inputs.target }}-${{ inputs.cache-key }}
        cache-on-failure: true

    - name: Determine if cross is needed
      id: needs-cross
      shell: bash
      run: |
        case "${{ inputs.target }}" in
          aarch64-unknown-linux-gnu|aarch64-pc-windows-msvc)
            echo "needed=true" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "needed=false" >> $GITHUB_OUTPUT
            ;;
        esac

    - name: Cache cross binary
      if: steps.needs-cross.outputs.needed == 'true'
      id: cache-cross
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cross
        key: ${{ runner.os }}-cross-${{ inputs.cross-version }}
        restore-keys: |
          ${{ runner.os }}-cross-

    - name: Install cross for cross-compilation builds
      if: steps.needs-cross.outputs.needed == 'true' && steps.cache-cross.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cargo install cross --git https://github.com/cross-rs/cross --tag ${{ inputs.cross-version }}
        cross --version

    - name: Verify Docker for cross
      if: steps.needs-cross.outputs.needed == 'true'
      shell: bash
      run: |
        docker --version
        docker info
