# Copyright (c) 2025 Erick Bourgeois, firestoned
# SPDX-License-Identifier: MIT

name: 'Build Rust Binary'
description: 'Builds Rust binary for specified target (uses cargo or cross)'
author: 'Erick Bourgeois <erick@firestoned.io>'

branding:
  icon: 'box'
  color: 'orange'

inputs:
  target:
    description: 'Rust target triple (e.g., x86_64-unknown-linux-gnu)'
    required: true

runs:
  using: composite
  steps:
    - name: Verify Rust toolchain
      uses: firestoned/github-actions/rust/verify-toolchain@main
      with:
        require-cargo: true

    - name: Build (release) - x86_64 Linux
      if: inputs.target == 'x86_64-unknown-linux-gnu'
      shell: bash
      run: cargo build --release --target ${{ inputs.target }} --verbose

    - name: Build (release) - ARM64 Linux with cross
      if: inputs.target == 'aarch64-unknown-linux-gnu'
      shell: bash
      run: cross build --release --target ${{ inputs.target }} --verbose

    - name: Build (release) - x86_64 Windows MSVC
      if: inputs.target == 'x86_64-pc-windows-msvc'
      shell: bash
      run: cargo build --release --target ${{ inputs.target }} --verbose

    - name: Build (release) - x86_64 Windows GNU
      if: inputs.target == 'x86_64-pc-windows-gnu'
      shell: bash
      run: cargo build --release --target ${{ inputs.target }} --verbose

    - name: Build (release) - ARM64 Windows with cross
      if: inputs.target == 'aarch64-pc-windows-msvc'
      shell: bash
      run: cross build --release --target ${{ inputs.target }} --verbose
