# Copyright (c) 2025 Erick Bourgeois, firestoned
# SPDX-License-Identifier: MIT

name: 'Generate SBOM'
description: 'Generate Software Bill of Materials (SBOM) in CycloneDX format using default naming conventions'
author: 'Erick Bourgeois <erick@firestoned.io>'

branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  format:
    description: 'Output format: json, xml, or both'
    required: false
    default: 'json'
  cyclonedx-version:
    description: 'Version of cargo-cyclonedx to use'
    required: false
    default: '0.5.7'
  describe:
    description: 'What to describe in SBOM: crate (entire crate with targets as subcomponents), binaries (separate SBOM per binary), or all-cargo-targets (separate SBOM per Cargo target)'
    required: false
    default: 'crate'
  target:
    description: 'Optional Rust target triple (e.g., x86_64-unknown-linux-gnu)'
    required: false
    default: ''
  package:
    description: 'Package to generate SBOM for (for workspaces with multiple packages)'
    required: false
    default: ''
  workspace:
    description: 'Generate SBOM for all workspace members'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Verify Rust toolchain
      uses: firestoned/github-actions/rust/verify-toolchain@main
      with:
        require-cargo: true

    - name: Cache cargo-cyclonedx
      id: cache-cyclonedx
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-cyclonedx
        key: ${{ runner.os }}-cargo-cyclonedx-${{ inputs.cyclonedx-version }}
        restore-keys: |
          ${{ runner.os }}-cargo-cyclonedx-

    - name: Install cargo-cyclonedx
      if: steps.cache-cyclonedx.outputs.cache-hit != 'true'
      shell: bash
      run: cargo install cargo-cyclonedx --version ${{ inputs.cyclonedx-version }}

    - name: Generate SBOM
      shell: bash
      run: |
        # Build base command
        BASE_CMD="cargo cyclonedx"

        # Add package or workspace flags
        # Note: cargo-cyclonedx 0.5.7 doesn't have --workspace flag
        # Use --all for workspace-wide generation
        if [ "${{ inputs.workspace }}" = "true" ]; then
          BASE_CMD="$BASE_CMD --all"
          echo "Generating SBOM for entire workspace (using --all)"
        elif [ -n "${{ inputs.package }}" ]; then
          BASE_CMD="$BASE_CMD --package ${{ inputs.package }}"
          echo "Generating SBOM for package: ${{ inputs.package }}"
        else
          BASE_CMD="$BASE_CMD --all"
          echo "Generating SBOM for current crate"
        fi

        # Add target if specified
        if [ -n "${{ inputs.target }}" ]; then
          BASE_CMD="$BASE_CMD --target ${{ inputs.target }}"
          echo "Target: ${{ inputs.target }}"
        fi

        # Add describe option
        BASE_CMD="$BASE_CMD --describe ${{ inputs.describe }}"
        echo "Describe mode: ${{ inputs.describe }}"

        # Generate JSON if requested
        if [ "${{ inputs.format }}" = "json" ] || [ "${{ inputs.format }}" = "both" ]; then
          echo "Generating SBOM in JSON format..."
          $BASE_CMD --format json
        fi

        # Generate XML if requested
        if [ "${{ inputs.format }}" = "xml" ] || [ "${{ inputs.format }}" = "both" ]; then
          echo "Generating SBOM in XML format..."
          $BASE_CMD --format xml
        fi

        # List generated files for verification
        echo ""
        echo "Generated SBOM files:"

        # Check root directory
        if compgen -G "*.cdx.*" > /dev/null 2>&1; then
          echo "Root directory SBOMs:"
          for file in *.cdx.*; do
            ls -lh "$file"
          done
        fi

        # Check each crate directory (for workspace with describe=crate)
        # cargo-cyclonedx generates SBOMs in each crate's directory
        if [ "${{ inputs.workspace }}" = "true" ] || [ -n "${{ inputs.package }}" ]; then
          echo ""
          echo "Searching for SBOMs in workspace crates..."
          # Find all Cargo.toml files (excluding target dirs and root if workspace)
          find . -name "Cargo.toml" -not -path "*/target/*" -not -path "*/.git/*" | while read cargo_file; do
            crate_dir=$(dirname "$cargo_file")
            # Check if SBOMs exist in this directory before trying to list them
            if compgen -G "$crate_dir/*.cdx.*" > /dev/null 2>&1; then
              echo ""
              echo "SBOMs in $crate_dir:"
              for file in "$crate_dir"/*.cdx.*; do
                ls -lh "$file"
              done
            fi
          done
        fi

        # Summary count
        echo ""
        total_sboms=$(find . -name "*.cdx.*" -not -path "*/target/*" -not -path "*/.git/*" -type f 2>/dev/null | wc -l | tr -d ' ')
        echo "Total SBOMs generated: $total_sboms"

        # Verify at least one SBOM was generated
        if [ "$total_sboms" -eq 0 ]; then
          echo "Error: No SBOM files were generated"
          exit 1
        fi
