# Copyright (c) 2025 Erick Bourgeois, firestoned
# SPDX-License-Identifier: MIT

name: 'Sign with Cosign'
description: 'Sign container images and artifacts using Cosign with keyless signing'
author: 'Erick Bourgeois <erick@firestoned.io>'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  image-digest:
    description: 'Docker image digest to sign (optional, for container images)'
    required: false
  image-tags:
    description: 'Comma-separated list of image tags to sign (optional, for container images)'
    required: false
  artifact-path:
    description: 'Path to artifact file to sign (optional, for files)'
    required: false
  registry:
    description: 'Container registry (e.g., ghcr.io)'
    required: false
    default: 'ghcr.io'
  repository:
    description: 'Image repository (e.g., firestoned/bindy)'
    required: false

outputs:
  signature-bundle:
    description: 'Path to the signature bundle (for artifacts)'
    value: ${{ steps.sign-artifact.outputs.bundle }}

runs:
  using: composite
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.7.0
      with:
        cosign-release: 'v2.4.1'

    - name: Sign container image (if image-digest provided)
      if: inputs.image-digest != ''
      shell: bash
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        echo "Signing container image with digest: ${{ inputs.image-digest }}"

        # Sign the image by digest (most reliable)
        cosign sign --yes \
          ${{ inputs.registry }}/${{ inputs.repository }}@${{ inputs.image-digest }}

        # Also sign by tags if provided
        if [ -n "${{ inputs.image-tags }}" ]; then
          IFS=',' read -ra TAGS <<< "${{ inputs.image-tags }}"
          for tag in "${TAGS[@]}"; do
            echo "Signing tag: ${tag}"
            cosign sign --yes \
              ${{ inputs.registry }}/${{ inputs.repository }}:${tag}
          done
        fi

        echo "✓ Container image signed successfully"

    - name: Sign artifact file (if artifact-path provided)
      id: sign-artifact
      if: inputs.artifact-path != ''
      shell: bash
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        echo "Signing artifact: ${{ inputs.artifact-path }}"

        # Sign the artifact (creates .sig and .cert files)
        cosign sign-blob --yes \
          --bundle "${{ inputs.artifact-path }}.bundle" \
          "${{ inputs.artifact-path }}"

        echo "bundle=${{ inputs.artifact-path }}.bundle" >> $GITHUB_OUTPUT
        echo "✓ Artifact signed successfully"
        echo "  - Signature bundle: ${{ inputs.artifact-path }}.bundle"

    - name: Verify signature (smoke test)
      if: inputs.image-digest != '' || inputs.artifact-path != ''
      shell: bash
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        echo "Running signature verification smoke test..."

        if [ -n "${{ inputs.image-digest }}" ]; then
          echo "Verifying container image signature..."
          cosign verify \
            --certificate-identity-regexp='https://github.com/${{ github.repository }}' \
            --certificate-oidc-issuer='https://token.actions.githubusercontent.com' \
            ${{ inputs.registry }}/${{ inputs.repository }}@${{ inputs.image-digest }} \
            | jq .
          echo "✓ Container signature verified"
        fi

        if [ -n "${{ inputs.artifact-path }}" ]; then
          echo "Verifying artifact signature..."
          cosign verify-blob \
            --bundle "${{ inputs.artifact-path }}.bundle" \
            --certificate-identity-regexp='https://github.com/${{ github.repository }}' \
            --certificate-oidc-issuer='https://token.actions.githubusercontent.com' \
            "${{ inputs.artifact-path }}"
          echo "✓ Artifact signature verified"
        fi

        echo "✓ All signature verifications passed"
